language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.9
  - nightly
notifications:
  email: false
git:
  depth: 99999999

after_script:
  - julia -e 'using Pkg, ClinicalTrialOptm; cd(joinpath(dirname(pathof(ClinicalTrialOptm)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  allow_failures:
    - julia: nightly    
  include:
    - stage: "Documentation"
      julia: 1.9
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using ClinicalTrialOptm; include(joinpath(dirname(pathof(ClinicalTrialOptm)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip  
      