name = "ClinicalTrialOptm"
uuid = "8796d277-b3d7-4205-96c1-d40f4fa55f1f"
authors = ["Hua Zhou <huazhou@ucla.edu>", "Arin Vansomphone <avansomphone@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
QuadGK = "2"
julia = "1.7"
